main color and font variables in sass, skeleton positions
Romkin7/geniobot.io-rush pull request #10
Opened 2021-06-24 21:28 UTC by jualiasha

2021-06-24 22:35 UTC, Romkin7 requested changes
Good Work, just few things to change for better development expereince in future for us.

2021-06-24 22:35 UTC, Romkin7 commented on tools/assets/sass/_variables.scss
> +$text-color: #ecebff; //almost white
Look how to setup variables file from my devdesign.fi site


/* Font */
$sourceSansPro: "Source Sans Pro", sans-serif;

/* Colors */
/* Primary colors */
$violet: #221e56;
$midnightblue: #0f0868;
$ligtermidnightBlue: #2b2a73;
$hotpink: #e55cb8;
$lightpink: #f27495;
$lavender: #e0e5f0;
$goldenrod: #e4ba0a;
$orangishRod: #f26b63;

/* Gray colors */
$gray100: #f8f8f8;
$gray200: #eeeeee;
$gray300: #e8e8e8;
$gray900: #434343;

/* Black and White colors */
$black: #000000;
$white: #ffffff;
$transparent: transparent;

/* Gradients */
$pinkLinearGradientToRight: linear-gradient(to right, $lightpink, $hotpink);
$orangeLinearGradientToRight: linear-gradient(
  to right,
  $goldenrod,
  $orangishRod
);
$pinkLinearGradientToRight80: linear-gradient(
  to right,
  rgba($lightpink, 0.8),
  rgba($hotpink, 0.8)
);
$radialGradientToCenter: linear-gradient($midnightblue, $ligtermidnightBlue);

/** Borders */
$grayBorder: 4px solid rgba(255, 255, 255, 0.5);
$darkGrayBorder: 2px solid rgba($gray300, 0.8);

/** Shadows */
$softShadow: 0 0 10px 5px rgba(0, 0, 0, 0.2);
$darkShadow: 0 0 8px 5px rgba(0, 0, 0, 0.3);

2021-06-24 22:35 UTC, Romkin7 commented on tools/dashboard/src/App.scss
> +		radial-gradient(50% 50% at 50% 50%, #201d47 0%, rgba(23, 21, 58, 0.91) 100%);
How to reuse gradients: 
<img width="706" alt="Screenshot 2021-06-25 at 1 31 33" src="https://user-images.githubusercontent.com/16634022/123340780-74983280-d555-11eb-9776-b64735c4e656.png">

2021-06-24 22:36 UTC, Romkin7 commented on tools/assets/sass/_variables.scss
> +$text-color: #ecebff; //almost white
you can also do like this: $midnightBlue80: rgba($midnightBlue, 0.8);

2021-06-25 13:55 UTC, jualiasha commented on tools/dashboard/src/App.scss
> +		radial-gradient(50% 50% at 50% 50%, #201d47 0%, rgba(23, 21, 58, 0.91) 100%);
changes done

2021-06-25 20:22 UTC, Romkin7 approved these changes

2021-06-26 10:08 UTC, Romkin7 requested changes

2021-06-26 10:08 UTC, Romkin7 commented on tools/assets/sass/shared-components/_dashboard-main.scss
> +	background: $patrickblue-linear;
don't use - in names, in js we will encounter problems, use 
1. $patrickblueLinear
or 2. $patrickblue_linear

2021-06-26 11:37 UTC, Romkin7 approved these changes
good work so far

2021-06-26 12:13 UTC, merged